VERSION = "0.1.0"
DEFAULT_BASE_URL = "https://api.framequery.com/v1/api"
DEFAULT_POLL_INTERVAL = 5.0
DEFAULT_TIMEOUT = 86400.0
DEFAULT_MAX_RETRIES = 2
DEFAULT_HTTP_TIMEOUT = 300.0
USER_AGENT = f"framequery-python/{VERSION}"
